package main

import (
	"flag"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/kaptinlin/jsonschema"
	"github.com/kaptinlin/jsonschema/internal/testutil"
)

func resetFlagsForTest() {
	flag.CommandLine = flag.NewFlagSet("schemagen", flag.ContinueOnError)
	flag.CommandLine.SetOutput(io.Discard)
	outputSuffix = flag.CommandLine.String("suffix", "_schema.go", "Output file suffix")
	packageName = flag.CommandLine.String("package", "", "Specify package name")
	verbose = flag.CommandLine.Bool("verbose", false, "Verbose output")
	dryRun = flag.CommandLine.Bool("dry-run", false, "Preview generated code without writing files")
	force = flag.CommandLine.Bool("force", false, "Force regeneration of all files")
	help = flag.CommandLine.Bool("help", false, "Show help message")
}

func findGenerationInfo(infos []*GenerationInfo, name string) *GenerationInfo {
	for _, info := range infos {
		if info.Name == name {
			return info
		}
	}
	return nil
}

func TestStructAnalyzer_AnalyzePackageBuildsDependencyGraph(t *testing.T) {
	// No t.Parallel(): companion tests in this package mutate process-wide stdout, flags, and cwd.
	analyzer, err := NewStructAnalyzer()
	require.NoError(t, err)

	infos, err := analyzer.AnalyzePackage("testdata")
	require.NoError(t, err)
	require.NotEmpty(t, infos)

	userInfo := findGenerationInfo(infos, "User")
	require.NotNil(t, userInfo)
	assert.Equal(t, "testdata", userInfo.Package)
	assert.True(t, analyzer.NeedsGeneration(userInfo))

	graph := analyzer.DependencyGraph()
	require.NotNil(t, graph)
	require.Contains(t, graph.nodes, "Category")
	assert.Contains(t, graph.edges["Category"], "Product")

	assert.True(t, analyzer.HasCircularDependencies())
	assert.NotEmpty(t, analyzer.CircularDependencies())
	assert.True(t, analyzer.NeedsRefGeneration("Category"))
	assert.Contains(t, analyzer.ReferencedStructs("Category"), "Product")
}

func TestCodeGenerator_ProcessPackageDryRunPrintsGeneratedSchema(t *testing.T) {
	// No t.Parallel(): captures process-wide stdout.
	generator, err := NewCodeGenerator(&GeneratorConfig{
		OutputSuffix: "_schema.go",
		DryRun:       true,
	})
	require.NoError(t, err)

	out := testutil.CaptureStdout(t, func() {
		require.NoError(t, generator.ProcessPackage("testdata"))
	})

	assert.Contains(t, out, "Code generated by schemagen. DO NOT EDIT.")
	assert.Contains(t, out, "func (s User) Schema() *jsonschema.Schema")
	assert.Contains(t, out, "jsonschema.Prop(\"id\"")
}

func TestFileWriter_WriteGeneratedCodeWritesFile(t *testing.T) {
	// No t.Parallel(): uses t.Chdir, which changes process-wide state.
	t.Chdir(t.TempDir())

	writer, err := NewFileWriter("_schema.go", "example", false, false)
	require.NoError(t, err)

	err = writer.WriteGeneratedCode("nested/user.go", "ignored", []MethodData{{
		Receiver:       "s User",
		StructName:     "User",
		Properties:     []string{"jsonschema.Prop(\"name\", jsonschema.String())"},
		RequiredFields: "\"name\"",
	}})
	require.NoError(t, err)

	data, err := os.ReadFile("nested/user_schema.go")
	require.NoError(t, err)

	assert.Contains(t, string(data), "package example")
	assert.Contains(t, string(data), "func (s User) Schema() *jsonschema.Schema")
	assert.Contains(t, string(data), "jsonschema.Required(\"name\")")
}

func TestFileWriter_WriteToFileRejectsParentTraversal(t *testing.T) {
	// No t.Parallel(): companion tests in this package mutate process-wide cwd.
	writer, err := NewFileWriter("_schema.go", "", false, false)
	require.NoError(t, err)

	err = writer.writeToFile("../escape.go", "package main\n")
	require.ErrorIs(t, err, jsonschema.ErrInvalidFilenamePath)
}

func TestCodeGenerator_ProcessPackageWithNoGeneratedStructs(t *testing.T) {
	// No t.Parallel(): captures process-wide stdout.
	dir := t.TempDir()
	err := os.WriteFile(filepath.Join(dir, "models.go"), []byte(`package sample

type plain struct {
	name string
}
`), 0o600)
	require.NoError(t, err)

	generator, err := NewCodeGenerator(&GeneratorConfig{
		OutputSuffix: "_schema.go",
		DryRun:       true,
		Verbose:      true,
	})
	require.NoError(t, err)

	out := testutil.CaptureStdout(t, func() {
		require.NoError(t, generator.ProcessPackage(dir))
	})

	assert.Contains(t, out, "No structs found requiring code generation")
}

func TestFileWriter_WriteGeneratedCodeReportsFormattingErrors(t *testing.T) {
	writer, err := NewFileWriter("_schema.go", "sample", true, false)
	require.NoError(t, err)

	err = writer.WriteGeneratedCode("bad.go", "sample", []MethodData{{
		Receiver:   "s Bad)",
		StructName: "Bad",
	}})
	require.ErrorIs(t, err, jsonschema.ErrCodeFormatting)
}

func TestShowHelp_PrintsUsage(t *testing.T) {
	// No t.Parallel(): mutates package-global flag state and captures process-wide stdout.
	resetFlagsForTest()

	out := testutil.CaptureStdout(t, func() {
		flag.CommandLine.SetOutput(os.Stdout)
		showHelp()
	})

	assert.Contains(t, out, "schemagen - JSON Schema Code Generation Tool")
	assert.Contains(t, out, "USAGE:")
	assert.Contains(t, out, "-suffix string")
}

func TestMain_HelpFlagPrintsUsage(t *testing.T) {
	// No t.Parallel(): mutates os.Args, package-global flag state, and captures process-wide stdout.
	resetFlagsForTest()
	oldArgs := os.Args
	defer func() {
		os.Args = oldArgs
	}()
	os.Args = []string{"schemagen", "-help"}

	out := testutil.CaptureStdout(t, func() {
		flag.CommandLine.SetOutput(os.Stdout)
		main()
	})

	assert.Contains(t, out, "schemagen - JSON Schema Code Generation Tool")
	assert.Contains(t, out, "EXAMPLES:")
}

func TestMain_DryRunProcessesPackage(t *testing.T) {
	// No t.Parallel(): mutates os.Args, package-global flag state, and captures process-wide stdout.
	resetFlagsForTest()
	oldArgs := os.Args
	defer func() {
		os.Args = oldArgs
	}()
	os.Args = []string{"schemagen", "-dry-run", "testdata"}

	out := testutil.CaptureStdout(t, func() {
		main()
	})

	assert.True(t, strings.Contains(out, "Generated code for") || strings.Contains(out, "func (s User) Schema() *jsonschema.Schema"))
}
